mkl-yeetable/mklyeetable/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^users/', include('users.urls')),
    path('about/', views.about),
    re_path(r'^test/', include('test.urls')),
    path('', views.index),
]

urlpatterns += staticfiles_urlpatterns()

mkl-yeetable/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup', views.signup_view, name="signup"),
    path('userhome', views.user_homepage, name="userhome"),
    path('login', views.login_view, name="login"),
    path('restaurantDirectory', views.restaurant_directory, name="restaurantDirectory"),
]

mkl-yeetable/users/models.py
from django.db import models

# Create your models here.


# class Hours(models.Model):
#     monday = models.CharField(max_length=200)
#     tuesday = models.CharField(max_length=200)
#     wednesday = models.CharField(max_length=200)
#     thursday = models.CharField(max_length=200)
#     friday = models.CharField(max_length=200)
#     saturday = models.CharField(max_length=200)
#     sunday = models.CharField(max_length=200)
#
#     def __str__(self):
#         return self.monday, self.tuesday


class Restaurant(models.Model):
    business_id = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    postal_code = models.CharField(max_length=200)
    latitude = models.CharField(max_length=200)
    longitude = models.CharField(max_length=200)
    stars = models.DecimalField(max_digits=11, decimal_places=1)
    review_count = models.IntegerField()
    is_open = models.BooleanField()
    categories = models.CharField(max_length=200)
    hours = models.CharField(max_length=200)
    # hours = models.ForeignKey(Hours, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

mkl-yeetable/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from yeelight import Bulb
from yeelight import discover_bulbs
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # log the user in
            return redirect('users:userhome')
    else:
        form = UserCreationForm()
    return render(request, 'users/signup.html', {'form': form})


# noinspection PyInterpreter
@csrf_exempt
def user_homepage(request):
    bulb = Bulb("192.168.1.167")
    # noinspection PyInterpreter,PyInterpreter
    if request.GET.get('connect'):
        print(request.GET.get('connect'))
        print("Discovering")
        print(discover_bulbs())
    elif request.GET.get('turnon'):
        print(request.GET.get('turnon'))
        print("Turning On")
        bulb.turn_on()
    elif request.GET.get('turnoff'):
        print(request.GET.get('turnoff'))
        print("Turning Off")
        bulb.turn_off()
    elif request.GET.get('dimming'):
        print(request.GET.get('dimming'))
        print("Dimming")
        bulb.set_brightness(1)
    elif request.GET.get('color'):
        print(request.GET.get('color'))
        print("Setting Color")
        bulb.set_color_temp(2700)
    elif request.GET.get('lecrepecafe'):
        print(request.GET.get('lecrepecafe'))
        print("Clicked Le Crepe Cafe")
        bulb.turn_on()
        bulb.set_color_temp(2700)
    elif request.GET.get('starbucks'):
        print(request.GET.get('starbucks'))
        print("Clicked Starbucks")
        bulb.turn_on()
        bulb.set_color_temp(6500)
    elif request.GET.get('jamba'):
        print(request.GET.get('jamba'))
        print("Clicked Jamba")
        bulb.turn_on()
        bulb.set_color_temp(6500)
    elif request.GET.get('panda'):
        print(request.GET.get('panda'))
        print("Clicked Panda")
        bulb.turn_on()
        bulb.set_color_temp(2700)
    else:
        print(request.GET.get('turnoff'))
        print("NO REQUEST")
    return render(request, 'users/userhome.html')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            return redirect('users:userhome')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})


def restaurant_directory(request):
    try:
        # test for specific restaurants
        myid = request.GET['id']
        print("id=" + myid)
        bulb = Bulb("192.168.1.167")
        if myid == '0':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            print("Da Spot")
        elif myid == '1':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("Dunkin' Donuts")
        elif myid == '2':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Govindas")
        elif myid == '3':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("Holoholo Grill")
        elif myid == '4':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Hot Tacos")
        elif myid == '5':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("Kamitoku Ramen")
        elif myid == '6':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("LL BBQ")
        elif myid == '7':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("Lasoon")
        elif myid == '8':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("Le Crepe Cafe")
        elif myid == '9':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("Panda Express")
        elif myid == '10':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Peace Cafe")
        elif myid == '11':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Punchbowl Cafe")
        elif myid == '12':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Sistah Truck")
        elif myid == '13':
            # do stuff to the light bulb
            print("Turning On")
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("The Bean Counter")
    except:
        print(request.GET)
    try:
        # test for locations
        locationid = request.GET['locationid']
        print("locationid=" + locationid)
        bulb = Bulb("192.168.1.167")
        if locationid == '0':
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("Center for Korean Studies")
        elif locationid == '1':
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Holmes Hall")
        elif locationid == '2':
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Krauss Hall")
        elif locationid == '3':
            bulb.turn_on()
            bulb.set_color_temp(6500)
            print("Paradise Palms")
        elif locationid == '4':
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("POST")
        elif locationid == '5':
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Shidler College of Business")
        elif locationid == '6':
            bulb.turn_on()
            bulb.set_color_temp(2700)
            print("Sustainability Courtyard")
    except:
        print(request.GET)
    return render(request, 'users/restaurantDirectory.html')

mkl-yeetable/users/templates/users/login.html
<!--{% load static from staticfiles %}-->

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>MKL YEETABLE</title>
  <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>
  <link rel="shortcut icon" href="">
  <link rel="stylesheet" href="{% static '/css/login.css' %}">
</head>
<body>
<img src="{% static '/images/logo.png' %}" id="logo"/>

<div class="form"
     style="
     background: -webkit-linear-gradient(#ffffff, #c1c1c1);
     background: linear-gradient(#ffffff, #c1c1c1);
">
  <h3>RETURNING USERS</h3>
  <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="LOGIN">
    <a href="signup"><h5 class="ui header right aligned" style="font-weight: normal">New? Register Now!</h5></a>
  </form>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div id="footer" class="footer-background" style="background-color: #292929; color: white;">
  <div class="ui three column grid container">
    <div class="column">
      <h4>HEADQUARTERS</h4>
      <hr/>
      <div class="ui list">
        <div class="item">POST 318-B</div>
      </div>
    </div>
    <div class="column">
      <h4>GITHUB</h4>
      <hr/>
      <div class="ui list">
        <div class="item"><a href="https://github.com/teammkl" style="color: white;">github.com/teammkl</a></div>
      </div>
    </div>
    <div class="column">
      <h4>CONTACT US</h4>
      <hr/>
      <div class="ui list">
        <div class="item">Email: yeetable@gmail.com</div>
        <div class="item">Phone: 1-808-420-9325</div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

mkl-yeetable/users/templates/users/signup.html
<!--{% load static from staticfiles %}-->

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>MKL YEETABLE</title>
  <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>
  <link rel="shortcut icon" href="">
  <link rel="stylesheet" href="{% static '/css/signup.css' %}">
</head>
<body>

<img src="{% static '/images/logo.png' %}" id="logo"/>

<div class="form"
     style="
     background: -webkit-linear-gradient(#ffffff, #c1c1c1);
     background: linear-gradient(#ffffff, #c1c1c1);
">
  <h3>CREATE ACCOUNT</h3>
  <form action="{% url 'users:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
    <a href="login"><h5 class="ui header right aligned" style="font-weight: normal">
      Already have an account? Click to Sign In</h5></a>
  </form>
</div>
<div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

<div id="footer" class="footer-background" style="background-color: #292929; color: white;">
  <div class="ui three column grid container">
    <div class="column">
      <h4>HEADQUARTERS</h4>
      <hr/>
      <div class="ui list">
        <div class="item">POST 318-B</div>
      </div>
    </div>
    <div class="column">
      <h4>GITHUB</h4>
      <hr/>
      <div class="ui list">
        <div class="item"><a href="https://github.com/teammkl" style="color: white;">github.com/teammkl</a></div>
      </div>
    </div>
    <div class="column">
      <h4>CONTACT US</h4>
      <hr/>
      <div class="ui list">
        <div class="item">Email: yeetable@gmail.com</div>
        <div class="item">Phone: 1-808-420-9325</div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

mkl-yeetable/users/templates/users/userhome.html
<!--{% load static from staticfiles %}-->

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <title>MKL YEETABLE</title>
  <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>
  <link rel="shortcut icon" href="">
  <link rel="stylesheet" href="{% static '/css/userhome2.css' %}">
</head>
<body>
<a href="{% url 'users:userhome' %}">
  <img src="{% static '/images/logo.png' %}" id="logo"/>
</a>

<div id="navBar" class="ui menu inverted four item">
  <!--<div id="coordinates" class="item">0</div>-->
  <a class="item" href="{% url 'users:userhome' %}"
     style="font-family: 'Julius Sans One', serif; padding: 20px; font-size: 20px;"
  >Home</a>
  <a class="item" href="{% url 'users:restaurantDirectory' %}"
     style="font-family: 'Julius Sans One', serif; padding: 20px; font-size: 20px;"
  >Restaurant Directory</a>
  <a class="item" href="{% url 'users:login' %}"
     style="font-family: 'Julius Sans One', serif; padding: 20px; font-size: 20px;"
  >Sign Out</a>
  <div class="item">
    <div class="ui search">
      <div class="ui icon input">
        <input class="prompt" type="text" placeholder="Search restaurants...">
        <i class="search icon"></i>
      </div>
      <div class="results"></div>
    </div>
  </div>
</div>

<div id="leftMenu" class="ui two column grid">
  <div class="four wide column">
    <div class="ui vertical fluid tabular menu">
      <div class="item">
        <h3 class="item ui header">Locations</h3>
        <div id="locationsMenu" class="ui right aligned container">
          <a href="restaurantDirectory?locationid=0" class="item">Center for Korean Studies</a>
          <a href="restaurantDirectory?locationid=1" class="item">Holmes Hall</a>
          <a href="restaurantDirectory?locationid=2" class="item">Krauss Hall</a>
          <a href="restaurantDirectory?locationid=3" class="item">Paradise Palms Café</a>
          <a href="restaurantDirectory?locationid=4" class="item">POST Building</a>
          <a href="restaurantDirectory?locationid=5" class="item">Shidler College of Business</a>
          <a href="restaurantDirectory?locationid=6" class="item">Sustainability Courtyard</a>
        </div>
      </div>
      <div class="item">
        <h3 class="item ui header">Restaurants</h3>
        <div id="restaurantNameMenu" class="ui right aligned container"></div>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="ui center aligned fluid container">
      <img src="{% static '/images/locationsUpperCampusMap.png' %}" alt="Upper Campus Locations" border="0"
           usemap="#upperMap"/>
      <map name="upperMap">
        <area shape="rect" coords="520,290,560,340" onmouseover="mouseOver(0)" onmouseout="mouseOut(0)"
              alt="Center for Korean Studies" href="restaurantDirectory?locationid=0">
        <area shape="rect" coords="160,495,200,545" onmouseover="mouseOver(1)" onmouseout="mouseOut(1)"
              alt="Holmes Hall" href="restaurantDirectory?locationid=1">
        <area shape="rect" coords="80,325,120,375" onmouseover="mouseOver(2)" onmouseout="mouseOut(2)"
              alt="Krauss Hall" href="restaurantDirectory?locationid=2">
        <area shape="rect" coords="395,275,430,325" onmouseover="mouseOver(3)" onmouseout="mouseOut(3)"
              alt="Paradise Palms Café" href="restaurantDirectory?locationid=3">
        <area shape="rect" coords="520,290,560,340" onmouseover="mouseOver(4)" onmouseout="mouseOut(4)"
              alt="POST Building" href="restaurantDirectory?locationid=4">
        <area shape="rect" coords="80,0,200,40" onmouseover="mouseOver(5)" onmouseout="mouseOut(5)"
              alt="Shidler College of Business, 1st Floor" href="restaurantDirectory?locationid=5">
        <area shape="rect" coords="130,345,185,415" onmouseover="mouseOver(6)" onmouseout="mouseOut(6)"
              alt="Sustainability Courtyard" href="restaurantDirectory?locationid=6">
      </map>
      <img src="{% static '/images/locationsLowerCampusMap.png' %}" alt="Lower Campus Locations" border="0"
           usemap="#Map"/>
      <div id="mapLabels" class="ui left pointing black labels">
        <div id="locationid0" class="ui right pointing label" style="font-weight: normal; display: none">
          <h4>Center for Korean Studies</h4>
          <p>Kamitoku Ramen</p>
        </div>
        <div id="locationid1" class="ui left pointing label" style="font-weight: normal; display: none">
          <h4>Holmes Hall</h4>
          <p>Sistah Truck</p>
        </div>
        <div id="locationid2" class="ui left pointing label" style="font-weight: normal; display: none">
          <h4>Krauss Hall</h4>
          <p>Hot Tacos</p>
        </div>
        <div id="locationid3" class="ui left pointing label" style="font-weight: normal; display: none">
          <h4>Paradise Palms Café</h4>
          <p>Dunkin' Donuts</p>
          <p>Holoholo Grill</p>
          <p>L&L Barbecue</p>
          <p>Lasoon</p>
          <p>Le Crêpe Café</p>
          <p>Panda Express</p>
        </div>
        <div id="locationid4" class="ui left pointing label" style="font-weight: normal; display: none">
          <h4>POST Building</h4>
          <p>Hot Tacos</p>
        </div>
        <div id="locationid5" class="ui left pointing label" style="font-weight: normal; display: none">
          <h4>Schidler College of Business</h4>
          <p>The Bean Counter</p>
        </div>
        <div id="locationid6" class="ui left pointing label" style="font-weight: normal; display: none">
          <h4>Sustainability Courtyard</h4>
          <p>Da Spot</p>
          <p>Govinda's</p>
          <p>Peace Cafe</p>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="footer" class="footer-background" style="background-color: #292929; color: white;">
  <div class="ui three column grid container">
    <div class="column">
      <h3>HEADQUARTERS</h3>
      <hr/>
      <div class="ui list">
        <div class="item">POST 318-B</div>
      </div>
    </div>
    <div class="column">
      <h3>GITHUB</h3>
      <hr/>
      <div class="ui list">
        <div class="item"><a href="https://github.com/teammkl" style="color: white;">github.com/teammkl</a></div>
      </div>
    </div>
    <div class="column">
      <h3>CONTACT US</h3>
      <hr/>
      <div class="ui list">
        <div class="item">Email: yeetable@gmail.com</div>
        <div class="item">Phone: 1-808-420-9325</div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

<script>
  const locationList = [
    "Center for Korean Studies",
    "Holmes Hall",
    "Krauss Hall",
    "Paradise Palms Café",
    "POST Building",
    "Shidler College of Business, 1st Floor",
    "Sustainability Courtyard"
  ];

  const data = [
    { name: "Da Spot", location: "Sustainability Courtyard", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Dunkin' Donuts", location: "Paradise Palms Café", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Govinda's", location: "Sustainability Courtyard", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Holoholo Grill", location: "Paradise Palms Café", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Hot Tacos", location: "Krauss Hall", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Kamitoku Ramen", location: "Center for Korean Studies", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "L&L Hawaiian Barbecue", location: "Paradise Palms Café", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Lasoon", location: "Paradise Palms Café", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Le Crêpe Café", location: "Paradise Palms Café", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Panda Express", location: "Paradise Palms Café", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Peace Cafe", location: "Sustainability Courtyard", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Punchbowl Cafe", location: "POST Building", hours: "Monday-Friday 10:00am - 2:00pm" },
    { name: "Sistah Truck", location: "Holmes Hall", hours: "Monday-Friday 10:00am - 2:00pm" },
    {
      name: "The Bean Counter",
      location: "Shidler College of Business, 1st Floor",
      hours: "Monday-Friday 10:00am - 2:00pm"
    }
  ];
  for (let i = 0; i < data.length; i++) {
    data[i].myid = i;
    for (let j = 0; j < locationList.length; j++) {
      if (data[i].location == locationList[j]) {
        data[i].locationid = j;
      }
    }
    createMenuItem(data[i]);
  }

  function createMenuItem(restaurantObj) {
    $('#restaurantNameMenu')
        .append(
            $('<a/>').attr("href", "restaurantDirectory?id=" + restaurantObj.myid)
                .addClass("item").text(restaurantObj.name));
  }

  $('.ui.search')
      .search({
        source: data,
        searchFields: ['name'],
        fields: {
          title: 'name',
        },
        onSelect: function (result, response) {
          console.log(result);
          console.log(response);
          console.log(result.myid);
          location.href = "restaurantDirectory" + "?id=" + result.myid;
          return true;
        }
      });

  $(function () {
    $(document).mousemove(function (e) {
      $('#coordinates').html('x: ' + e.pageX + ' y : ' + e.pageY);
    });
  })

  function placeDiv(x_pos, y_pos, elementid) {
    let d = document.getElementById(elementid);
    d.style.position = "absolute";
    d.style.left = x_pos + 'px';
    d.style.top = y_pos + 'px';
  }

  function mouseOver(locationid) {
    document.getElementById("locationid" + locationid).style.display = "inline-block";
  }

  function mouseOut(locationid) {
    document.getElementById("locationid" + locationid).style.display = "none";
  }

  function positionMapLabels() {
    placeDiv(335, 300, 'locationid0');
    placeDiv(205, 510, 'locationid1');
    placeDiv(125, 335, 'locationid2');
    placeDiv(440, 215, 'locationid3');
    placeDiv(205, 510, 'locationid4');
    placeDiv(135, 10, 'locationid5');
    placeDiv(180, 350, 'locationid6');
  }

  positionMapLabels();
</script>